name: JRPG-UI-Module CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update Version
        shell: bash
        id: set-version
        run: echo "::set-output name=version::$(node ./.github/workflows/set-version.js ${{ github.ref }})"
      - name: Install Dependencies
        run: npm install
      - name: Build Module
        run: |
          mkdir -p dist
          cp -r ./* dist/
      - name: Create Release
        id: create_versioned_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.set-version.outputs.version }}
          release_name: "Release ${{ steps.set-version.outputs.version }}"
          draft: false
          prerelease: false
          artifacts: './dist/module.json,./dist/jrpg-ui-module.zip'
