name: JRPG-UI-Module CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Substitute Manifest and Download Links For Versioned Ones
        id: sub_manifest_link_version
        uses: microsoft/variable-substitution@v1
        with:
          files: 'module.json'
        env:
          version: ${{github.event.release.tag_name}}
          url: https://github.com/Niqu3d/jrpg-ui-module
          manifest: https://github.com/Niqu3d/jrpg-ui-module/releases/latest/download/module.json
          download: https://github.com/Niqu3d/jrpg-ui-module/releases/latest/download/jrpg-ui-module.zip

    - name: Create Module Archive
        run:  zip -r ./jrpg-ui-module.zip module.json image/ scripts/ styles/ templates/ README.md

     - name: Update Release With Files
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          name: ${{ github.event.release.name }}
          draft: false
          prerelease: ${{ github.event.release.prerelease }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './module.json, ./jrpg-ui-module.zip'
          tag: ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}
